version: '3'
services:
  postgres:
    image: postgres:10
    env_file: .env
    ports:
      - "5432:5432"
    restart: always
  app:
      build: 
        context: app
        dockerfile: Dockerfile
      ports:
        - 5000:5000
      depends_on:
        - postgres
      entrypoint: ["python", "run.py"]
      restart: always